### ISSUE TITLE
Error: Cannot find module 'xregexp' Atom 1.5.0 after update of linter-phpmd to 1.4.1

### ISSUE THREAD

**Issue by Eldair** [AtomLinter/linter-phpmd#42]
Below is the error code which appears on save and on lint command

`Error: Cannot find module 'xregexp'
Error: Cannot find module 'xregexp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Kristijan\AppData\Local\atom\app-1.5.0-beta1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Kristijan\AppData\Local\atom\app-1.5.0-beta1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.parse (C:\Users\Kristijan\.atom\packages\linter-phpmd\node_modules\atom-linter\lib\helpers.js:302:15)
    at file:///C:/Users/Kristijan/.atom/packages/linter-phpmd/lib/main.coffee:61:26
    at process._tickCallback (node.js:368:9)`

**Comment by Arcanemagus** [comment]
That shouldn't even be something that is being loaded any more, unless either `apm` didn't update you properly, or I missed another bit of code when updating it a while back. Checking on that now...

**Comment by Arcanemagus** [comment]
Nope, looks like it's just `apm` not having updated the dependencies properly. Can you try uninstalling and re-installing the plugin?

**Comment by Eldair** [comment]
Yeah, that did the trick, Sorry for bothering you.

**Comment by Arcanemagus** [comment]
Not a problem! Glad it was a simple fix :wink:
